---
- name: Deploy Docker Container
  hosts: localhost
  tasks:
    - name: Pull Docker Image from Docker Hub 
      docker_image:
              name: h3md0cker/scicalc:test2
              source: pull
