---
- name: Deploy Docker Container
  hosts: ubuntu18
  remote_user: hemc
  tasks:
    - name: Pull Docker Image from Docker Hub 
      docker_image:
              name: h3md0ck3r/scicalc
              source: pull
